BEGIN;

DROP TABLE IF EXISTS error_groups CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS errors CASCADE;
DROP TABLE IF EXISTS ingestion_failures CASCADE;
DROP TABLE IF EXISTS sdk_sessions CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS replays CASCADE;
DROP TABLE IF EXISTS cron_checkins CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
DROP TABLE IF EXISTS logs CASCADE;
DROP TABLE IF EXISTS metrics CASCADE;
DROP TABLE IF EXISTS traces CASCADE;
DROP TABLE IF EXISTS spans CASCADE;

COMMIT;
